### ISSUE TITLE
As a Gamemaster, I want to decide how many players play with me.

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#10]
Acceptance Criteria:

- [x] When the user is the one starting the game, he/she can choose if 1, 2 or 3 other player can join
- [x] When a user joins a game someone else initiated, he/she has no choice on how many players the game is going to have

Development Taks:

- [x] sopra-fs22-group-24/client#13
- [x] sopra-fs22-group-24/client#14

**Comment by flruee** [comment]
Done in 975a0d55e92b3d67e2fbb17835f43cff0adae2c8
