### ISSUE TITLE
As a player I have to play a matching card or if not available press the launcher button in order to end my turn.

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#15]
Acceptance Criteria:

- [x] A player plays a matching card (same color, same number, same symbol or special card if applicable)
- [x] Or player presses the launcher button and randomly receives some cards (to be determined what the upper ceiling is)
- [x] The next player then starts their turn.

Development Tasks:
- [ ] sopra-fs22-group-24/client#18
- [x] sopra-fs22-group-24/client#19
- [x] #65
- [x] #66
- [x] #67

**Comment by flruee** [comment]
Done a long time ago, was probably forgotten to close.
