### ISSUE TITLE
As a player I want to play a “Reverse” card in order to reverse the turn order

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#16]
Acceptance Criteria:

- [ ] A player can play the “Reverse” card if the color or the symbol matches. 
- [ ] The order of play is reversed, i.e. the next player to play is the player that played before

Developement Tasks:
- [x] #68

**Comment by flruee** [comment]
Done in ff8553bed4dd0f17dc85acb59565e3dbf16cdb52 by Mauro
