### ISSUE TITLE
As a player I want to play a “Hit 2” card in order to force the next player to press the launcher button twice and skip their turn.

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#20]
- [x] A player can play the “Hit 2” card if the color matches. 
- [x] The next player has the only option to press the launcher button twice (could also be done automatically) and forfeits the rest of their turn
- [x] The player after the next player starts their turn

**Comment by flruee** [comment]
Done
The victim will draw automatically
