### ISSUE TITLE
As a player I want to be sure that it’s not allowed for other players and myself to play unfairly

### ISSUE THREAD

**Issue by maurohirt** [sopra-fs22-group-24/server#23]
- [x] It’s not allowed for players to play unfairly and don’t follow the game-rules.
- [x] Every time a player wants to make a move, which doesn’t match the game rules, it will get hindered by the game.

**Comment by flruee** [comment]
Data Validation is in place and so are unit tests (mostly). Since all game logic resides in the backend and the callee always gets authenticated (at least in the game) this issue should be closed. The wording of this issue is however a bit off and there should have been acceptance criteria.
